# Generated by Django 3.1.3 on 2021-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210125_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_done',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
